# Generated by Django 4.1.4 on 2022-12-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
